# Generated by Django 5.2.1 on 2025-05-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=15)),
                ('moviedescription', models.CharField(max_length=10)),
                ('moviefare', models.IntegerField()),
            ],
        ),
    ]
